name: flutter_banco_douro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/banner.png
    - assets/images/icon_add_account.png
    - assets/images/logo.png
    - assets/images/stars.png
    - assets/images/stars.png
    
